### ISSUE TITLE
elf2cube.py is incompatible with numpy.

### ISSUE THREAD

**Issue by Jeffery-Li0513** [patrickmelix/VASP-tools#1]
Which version of numpy should I use?

**Comment by Jeffery-Li0513** [comment]
which version of python should I use? Now I use python3.8

**Comment by patrickmelix** [comment]
Hi @Jeffery-Li0513 ,

Only very basic numpy functions are used, I expect any numpy version to work fine.

Same goes for Python, I'm on 3.7 but I do not see why 3.8 should not work. As long as you have pymatgen this should not matter.

Best,
Patrick
